# Site settings
title: Cris Noel | Web Developer
email: crisnoel12@gmail.com
description: What's up, I'm Cris and I'm a Web Developer currently based in Cavite, Philippines.
url: "crisnoel.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: crisnoel91
github_username: crisnoel12
codepen_username: crisnoel12
twitter_username: crisnoel12

# Build settings
markdown: kramdown
permalink: "/:title"
gems:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: '/blog/page:num/'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - gulpfile.js
  - yarn.lock
  - firebase.json
  - css/dist/styles.css
  - css/dist/styles.css.map
  - css/vendor/prism.css
  - js/dist/index.js
  - js/dist/index.js.map
  - js/filterPosts.js
  - js/main.js
  - js/myNav.js
  - js/myWaypoint.js
  - js/vendor/matchHeight.js
  - debug.log

defaults:
- scope:
    path: ''
    type: drafts
  values:
    author: Cris Noel
    permalink: "/blog/:title"
    layout: post
    image: default-blog-img.png
    description: This is the default description. Please add a description field to the corresponding post.
    isPost: true
- scope:
    path: ''
    type: posts
  values:
    author: Cris Noel
    permalink: "/blog/:title"
    layout: post
    image: default-blog-img.png
    comments: true
    description: This is the default description. Please add a description field to the corresponding post.
    isPost: true
- scope:
    path: ''
    type: pages
  values:
    layout: page